# Generated by Django 4.2.5 on 2023-11-28 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_products_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='size',
        ),
    ]
