# Generated by Django 4.2.5 on 2023-11-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_products_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_image',
            field=models.FilePathField(path='/media/'),
        ),
    ]
