# Generated by Django 4.2.5 on 2023-11-29 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_products_product_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='TrendProducts',
        ),
    ]
