# Generated by Django 4.2.5 on 2023-11-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_products_trendproducts'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_description', models.TextField(max_length=1000)),
                ('product_price', models.FloatField()),
                ('image', models.ImageField(upload_to='all_products')),
            ],
        ),
    ]
