# Generated by Django 4.2.5 on 2023-11-29 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_allproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allproducts',
            name='image',
            field=models.ImageField(upload_to='all_product'),
        ),
    ]
