# Generated by Django 4.2.5 on 2023-11-29 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_allproducts_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllProducts',
        ),
    ]
