# Generated by Django 4.2.5 on 2023-12-05 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='AllProducts',
        ),
    ]
