# Generated by Django 4.2.5 on 2023-12-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_products_allproducts'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=200)),
                ('bdescription', models.TextField(max_length=1000)),
                ('bprice', models.FloatField()),
                ('b_image', models.ImageField(upload_to='block_products')),
            ],
        ),
        migrations.CreateModel(
            name='PaverProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=200)),
                ('pdescription', models.TextField(max_length=1000)),
                ('pprice', models.FloatField()),
                ('p_image', models.ImageField(upload_to='paver_products')),
            ],
        ),
        migrations.CreateModel(
            name='SlabProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setname', models.CharField(max_length=200)),
                ('sdescription', models.TextField(max_length=1000)),
                ('sprice', models.FloatField()),
                ('s_image', models.ImageField(upload_to='slab_products')),
            ],
        ),
        migrations.DeleteModel(
            name='AllProducts',
        ),
    ]
