# Generated by Django 4.2.5 on 2023-12-06 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_blockproducts_paverproducts_slabproducts_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slabproducts',
            old_name='setname',
            new_name='sname',
        ),
    ]
